Document: kcm
Title: Debian kcm Manual
Author: <insert document author here>
Abstract: This manual describes what kcm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kcm/kcm.sgml.gz

Format: postscript
Files: /usr/share/doc/kcm/kcm.ps.gz

Format: text
Files: /usr/share/doc/kcm/kcm.text.gz

Format: HTML
Index: /usr/share/doc/kcm/html/index.html
Files: /usr/share/doc/kcm/html/*.html
